spec:
  template:
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Shanghai
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-jks
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: @spring.profiles.active@
            - name: JAVA_OPTIONS
              value: >
                -Djavax.net.ssl.trustStore=/mnt/secrets/mongo.jks 
                -Djavax.net.ssl.trustStorePassword=$(STORE_PASSWORD)
          volumeMounts:
            - name: mongo-jks
              mountPath: /mnt/secrets
              readOnly: true
      volumes:
        - name: mongo-jks
          secret:
            secretName: "mongo-jks"
            items:
              - key: mongo-truststore.jks
                path: mongo.jks
      serviceAccountName: @k8s-reader@