spring:
  application:
    name: framework-user
  cloud:
    kubernetes:
      loadbalancer:
        #根据 pod ip 轮询负载均衡
        mode: pod
  data:
    mongodb:
      database: user
      #&readPreference=secondaryPreferred 事务中不能读从库
      #&minPoolSize=10&maxPoolSize=10
      uri: mongodb://vipserver.com:31181,vipserver.com:31182,vipserver.com:31183/?ssl=true&authSource=admin&w=majority&wtimeoutMS=60000&readConcernLevel=local&readPreference=secondaryPreferred&maxIdleTimeMS=3600000
  redis:
    database: 0
    cluster:
      nodes: 192.168.209.132:6379,192.168.209.133:6379,192.168.209.134:6379,192.168.209.132:6380,192.168.209.133:6380,192.168.209.134:6380
  elasticsearch:
    rest:
      uris: 192.168.209.135:9200
      username: elastic

security:
  oauth2:
    resource:
      tokenInfoUri: http://localhost:8910/oauth/check_token
    client:
      client-id: localhost
      client-secret: localhost

server:
  port: 8920

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,restart

app:
  security:
    ignore:
      urls: /**

#sentry:
#  dsn: http://34854421b6824eb1b03a5df6a9db64a5@192.168.209.12:9000/2
#  environment: prod546ab122c057811b28d4cb62ff5987650c349427
#  release:
#  logging:
#    enabled: true
#    minimum-breadcrumb-level: info
#    minimum-event-level: warn